config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :fields

  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  # get 'service-worker' => 'rails/pwa#service_worker', as: :pwa_service_worker
  # get 'manifest' => 'rails/pwa#manifest', as: :pwa_manifest

  # Defines the root path route ("/")
  root "fields#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/field.rb
class Field < ApplicationRecord
  before_save :calculate_area

  validates_presence_of :name, :shape

  def shape_as_geojson
    RGeo::GeoJSON.encode(shape)
  end

  private

  def calculate_area
    utm_factory = RGeo::Geographic.projected_factory(
      projection_proj4: '+proj=utm +zone=36 +datum=WGS84 +units=m +no_defs',
      projection_srid: 32636,
      geographic_srid: 4326
    )
    projected_multipolygon = RGeo::Feature.cast(shape, factory: utm_factory, project: true)
    self.area = projected_multipolygon.area
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  def default_response(resource, status, template)
    respond_to do |format|
      if status == :created || status == :ok
        format.html { redirect_to resource, notice: "#{resource.class.name} was successfully #{status == :created ? 'created' : 'updated'}." }
        format.json { render template, status: status, location: resource }
      else
        format.html { render template, status: status }
        format.json { render json: resource.errors, status: status }
      end
    end
  end
end

app/controllers/concerns/field_params.rb
module FieldParams
  extend ActiveSupport::Concern

  def field_params
    params.require(:field).permit(:name)
  end

  def shape_attr
    shape_geojson = params[:field][:shape]
    factory = RGeo::Geographic.spherical_factory(srid: 4326)
    if is_wkt?(shape_geojson)
      factory.parse_wkt(shape_geojson)
    elsif is_geojson?(shape_geojson)
      geo_params = RGeo::GeoJSON.decode(shape_geojson, json_parser: :json)
      factory.multi_polygon([geo_params])
    end
  end

  private

  def is_wkt?(input)
    input.is_a?(String) && input.strip.match?(/\A(POINT|LINESTRING|POLYGON|MULTIPOLYGON|GEOMETRYCOLLECTION)/i)
  end

  def is_geojson?(input)
    input.is_a?(String) && input.strip.start_with?("{") && input.include?('"type"')
  end
end

app/controllers/fields_controller.rb
class FieldsController < ApplicationController
  include FieldParams

  before_action :set_field, only: %i[show edit update destroy]

  def index
    @fields = Field.all
    @geojsons = @fields.map(&:shape_as_geojson)
  end

  def show
    @geojson = @field.shape_as_geojson
  end

  def new
    @field = Field.new
  end

  def edit
    @geojson = @field.shape_as_geojson
  end

  def create
    @field = Field.new(field_params)
    @field.shape = shape_attr
    return default_response(@field, :created, :show) if @field.save

    default_response(@field, :unprocessable_entity, :new)
  end

  def update    
    @field.name = field_params[:name]
    @field.shape = shape_attr
    return default_response(@field, :ok, :show) if @field.save

    default_response(@field, :unprocessable_entity, :edit)
  end

  def destroy
    @field.destroy!

    respond_to do |format|
      format.html { redirect_to fields_path, status: :see_other, notice: "Field was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_field
    @field = Field.find(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/fields_helper.rb
module FieldsHelper
end

app/views/fields/_field.html.erb
<div id="<%= dom_id field %>">
  <p>
    <strong>Name:</strong>
    <%= field.name %>
  </p>

  <p>
    <strong>Area:</strong>
    <%= field.area %>
  </p>

</div>

app/views/fields/edit.html.erb
<h1>Edit Field</h1>

<div class="field-container">
  <%= form_with(model: @field, id: "edit-feature-form") do |form| %>
    <% if @field.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(@field.errors.count, "error") %> prohibited this field from being saved:</h2>

        <ul>
          <% @field.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :name, "Field Name" %>
      <%= form.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :area, "Area (sq meters)" %>
      <%= form.number_field :area, step: 0.01, class: "form-control", readonly: true, id: "field_area" %>
    </div>

    <div class="form-group">
      <strong>Geometry (Shape):</strong>
      <div id="map" class="map-container" style="height: 400px;"></div>
      <%= form.hidden_field :shape %>
    </div>

    <div class="form-actions">
      <%= form.submit "Save Changes", class: "btn-save" %>
      <%= link_to 'Cancel', field_path(@field), class: "btn-cancel" %>
    </div>
  <% end %>
</div>

<script>
  document.addEventListener("DOMContentLoaded", function() {
    function fixCoordinateOrder(coordinates) {
      return coordinates.map(function (polygon) {
        return polygon.map(function (ring) {
          return ring.map(function (coord) {
            return [coord[1], coord[0]];
          });
        });
      });
    }

    var osmUrl = 'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png';
    var osm = L.tileLayer(osmUrl, { maxZoom: 18 });
    var map = new L.Map('map', { center: new L.LatLng(49.520942, 31.811126), zoom: 13 }); 
    var drawnItems = L.featureGroup().addTo(map);
    var geoLayer = L.geoJSON(<%= raw @geojson.to_json %>, {
      onEachFeature: function (feature, layer) {
        if (feature.type === 'MultiPolygon') {
          var coordinates = fixCoordinateOrder(feature.coordinates)
          coordinates.forEach(function (polygonCoords) {
            var polygon = L.polygon(polygonCoords);
            drawnItems.addLayer(polygon);
          });
        } else {
          drawnItems.addLayer(layer);
        }
      }
    });
    L.control.layers({
      'osm': osm.addTo(map),
      "google": L.tileLayer('http://www.google.cn/maps/vt?lyrs=s@189&gl=cn&x={x}&y={y}&z={z}', { attribution: 'google' })
    }, { drawlayer: drawnItems }, { position: 'topleft', collapsed: false }).addTo(map);
    map.fitBounds(geoLayer.getBounds());

    map.addControl(new L.Control.Draw({
      draw: false,
      edit: {
        featureGroup: drawnItems,
        remove: true
      }
    }));

    function saveShapeAndArea(layer) {
      var geojson = layer.toGeoJSON();
      var geojsonString = JSON.stringify(geojson);
      document.getElementById('field_shape').value = geojsonString;
    }

    map.on(L.Draw.Event.EDITED, function(event) {
      event.layers.eachLayer(function(layer) {
        saveShapeAndArea(layer);
      });
    });
  });
</script>

app/views/fields/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Fields</h1>

<table class="fields-table">
  <thead>
    <tr>
      <th>Field Name</th>
      <th>Area (sq meters)</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @fields.each do |field| %>
      <tr>
        <td><%= link_to field.name, field_path(field) %></td>
        <td><%= field.area.round(2) %></td>
        <td>
          <%= link_to 'Show', field_path(field), class: "btn-show" %> |
          <%= link_to 'Edit', edit_field_path(field), class: "btn-edit" %>
        </td>
      </tr>
    <% end %>
  </tbody>

  <div id="map" class="map-container" style="height: 400px;"></div>
</table>

<%= link_to "New field", new_field_path %>

<script>
  document.addEventListener("DOMContentLoaded", function() {
    var osmUrl = 'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png';
    var osm = L.tileLayer(osmUrl, { maxZoom: 18 });
    var map = new L.Map('map', { center: new L.LatLng(45, 10), zoom: 3 }); 
    var drawnItems = L.featureGroup().addTo(map);

    L.control.layers({
      'osm': osm.addTo(map),
      "google": L.tileLayer('http://www.google.cn/maps/vt?lyrs=s@189&gl=cn&x={x}&y={y}&z={z}', { attribution: 'google' })
    }, { drawlayer: drawnItems }, { position: 'topleft', collapsed: false }).addTo(map);

    <%= raw @geojsons.to_json %>.map((shape) => L.geoJSON(shape).addTo(map))
  });
</script>

app/views/fields/new.html.erb
<h1>New field</h1>

<div class="field-container">
  <%= form_with(model: @field) do |form| %>
    <% if @field.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(@field.errors.count, "error") %> prohibited this field from being saved:</h2>

        <ul>
          <% @field.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :name, "Field Name" %>
      <%= form.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <strong>Geometry (Shape):</strong>
      <div id="map" class="map-container" style="height: 400px;"></div>
      <%= form.hidden_field :shape %>
    </div>

    <div class="form-actions">
      <%= form.submit "Save", class: "btn-save" %>
      <%= link_to "Back to fields", fields_path, class: "btn-cancel" %>
    </div>
  <% end %>
</div>

<script>
  document.addEventListener("DOMContentLoaded", function() {
    var osmUrl = 'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png';
    var osm = L.tileLayer(osmUrl, { maxZoom: 18 });
    var map = new L.Map('map', { center: new L.LatLng(49.520942, 31.811126), zoom: 13 }); 
    var drawnItems = L.featureGroup().addTo(map);

    L.control.layers({
      'osm': osm.addTo(map),
      "google": L.tileLayer('http://www.google.cn/maps/vt?lyrs=s@189&gl=cn&x={x}&y={y}&z={z}', {
          attribution: 'google'
      })
    }, { drawlayer: drawnItems }, { position: 'topleft', collapsed: false }).addTo(map);
    map.addControl(new L.Control.Draw({
      edit: { featureGroup: drawnItems, poly: { allowIntersection: false } },
      draw: {
        polygon: {
          allowIntersection: false,
          showArea: true
        },
        marker: false,
        polyline: false,
        rectangle: false,
        circle: false
      }
    }));

    map.on(L.Draw.Event.CREATED, function (event) {
      var layer = event.layer;
      var geojson = layer.toGeoJSON();
      var geojsonString = JSON.stringify(geojson);
      drawnItems.addLayer(layer);
      document.getElementById('field_shape').value = geojsonString;
    });
  });
</script>

app/views/fields/show.html.erb
<p style="color: green"><%= notice %></p>

<h1>Field Details</h1>

<div class="field-details-container">
  <div class="field-details">
    <strong>Field Name:</strong> <%= @field.name %>
  </div>

  <div class="field-details">
    <strong>Area (sq meters):</strong> <%= @field.area.round(2) %>
  </div>

  <div class="field-details">
    <strong>Geometry (Shape):</strong>
    <div id="map" class="map-container"></div>
  </div>

  <div class="form-actions">
    <%= link_to 'Edit', edit_field_path(@field), class: "btn-edit" %> |
    <%= link_to 'Back', fields_path, class: "btn-back" %>
    <%= button_to "Destroy this field", @field, method: :delete, class: "btn-destroy mt-2"  %>
  </div>
</div>

<script>
  document.addEventListener("DOMContentLoaded", function() {
    var map = L.map('map').setView([0, 0], 2);

    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
      maxZoom: 19,
    }).addTo(map);

    var geoLayer = L.geoJSON(<%= raw @geojson.to_json %>).addTo(map);
    map.fitBounds(geoLayer.getBounds());
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Postgis App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=" crossorigin=""/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet.draw/1.0.4/leaflet.draw.css"/>
    <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js" integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=" crossorigin=""></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet.draw/1.0.4/leaflet.draw.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>